// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzNa5TnFvChjNwDUIMbxBejY2-htsM2XY',
    appId: '1:165297946760:web:79cc9b2740a17ebd0b9f3d',
    messagingSenderId: '165297946760',
    projectId: 'smartscool-a9d3c',
    authDomain: 'smartscool-a9d3c.firebaseapp.com',
    storageBucket: 'smartscool-a9d3c.firebasestorage.app',
    measurementId: 'G-VFZ71JTMT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtazgEcj-Hp-Zx052mlQUB1xU7GtF8JxY',
    appId: '1:165297946760:android:a7ba0809991dfec00b9f3d',
    messagingSenderId: '165297946760',
    projectId: 'smartscool-a9d3c',
    storageBucket: 'smartscool-a9d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKG8sHqyV5hldb2Kbzm8oS7qQtYT1vzgg',
    appId: '1:165297946760:ios:6f3abaf62911803a0b9f3d',
    messagingSenderId: '165297946760',
    projectId: 'smartscool-a9d3c',
    storageBucket: 'smartscool-a9d3c.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKG8sHqyV5hldb2Kbzm8oS7qQtYT1vzgg',
    appId: '1:165297946760:ios:6f3abaf62911803a0b9f3d',
    messagingSenderId: '165297946760',
    projectId: 'smartscool-a9d3c',
    storageBucket: 'smartscool-a9d3c.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzNa5TnFvChjNwDUIMbxBejY2-htsM2XY',
    appId: '1:165297946760:web:1f42d4f4168c1e0f0b9f3d',
    messagingSenderId: '165297946760',
    projectId: 'smartscool-a9d3c',
    authDomain: 'smartscool-a9d3c.firebaseapp.com',
    storageBucket: 'smartscool-a9d3c.firebasestorage.app',
    measurementId: 'G-Y8LQKKT5Q1',
  );
}
